# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RC_4th_MangoPlate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RC_4th_MangoPlate
  pod 'KakaoSDK'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'

end
